### ISSUE TITLE
Display problem when importing a workflow saved on a screen with another resolution

### ISSUE THREAD

**Issue by CRLbazin** [alyssaxuu/flowy#101]
Hello,

If I load a previously saved workflow with a screen with a specific resolution onto another screen with a different resolution, the blocks are moved and the arrows point to white. 

After analyzing a bit, I realized that it is the reaarangeMe() call in the flowy.load function that is the problem.

If I comment on this reaarangeMe(), everything looks good.
Is this normal? What is the purpose of this call? 

![saved](https://user-images.githubusercontent.com/1326265/90952202-003ac180-e462-11ea-9258-cb0b1e30b935.png)

![loaded](https://user-images.githubusercontent.com/1326265/90952201-003ac180-e462-11ea-996c-a81dd1ca152a.png)

**Comment by lambdabyte** [comment]
> The problem is not related to the screen resolution but to the dimensions of the canva

I am having the same issue. I've tried setting specific pixel values, vh/vw, percentages, as well as keeping the canvas dimensions the same regardless of window size, as well as responsive. Could you elaborate on the issue's relation to canvas dimensions?

**Comment by ribaslipe** [comment]
I'm having the same problem, whenever I import it is with the wrong assembly, does anyone have any suggestions?

**Comment by alyssaxuu** [comment]
Just fixed it with the new updates (also fixing some other issues related to canvas positioning and offsets).
