### ISSUE TITLE
Conditional snap when move blocks inside canvas

### ISSUE THREAD

**Issue by jonasschen** [alyssaxuu/flowy#107]
Conditional snap works perfectly when create a new block in canvas.
But when moving a block to another connection, the method is not triggered.
How can i solve this?

**Comment by jonasschen** [comment]
I found the answer here #93

**Comment by hamzaGit19** [comment]
Hi @jonasschen 
I am trying to follow the answer too. But I'm not sure where exactly to put that piece of code. Can you please help me out?
