### ISSUE TITLE
iPad support 

### ISSUE THREAD

**Issue by MostafaNawara** [alyssaxuu/flowy#11]
I’m trying to use the demo with iPad 2018 but it’s not working

**Comment by benhid** [comment]
Could be related to https://github.com/alyssaxuu/flowy/issues/6

**Comment by alyssaxuu** [comment]
Yep, I am aware of the issue. Click events & getting the cursor position work differently in mobile. Working on it!

**Comment by alyssaxuu** [comment]
Added full mobile support.
