### ISSUE TITLE
how to add node programmatically 

### ISSUE THREAD

**Issue by Rohitgta77** [alyssaxuu/flowy#110]
Hello,
I have a Json , I want to Generate node Programmatically by using below JSON.

```
//---------------------DEMO JSON ---------------------------//
{
	"blockarr": [
		{
			"parent": -1,
			"id": 0
		},
		{
			"parent": 0,
			"id": 1
		}
	],
	"blocks": [
		{
			"id": 0,
			"parent": -1,
			"data": [
				{
					"name": "id",
					"value": ""
				},
				{
					"name": "name",
					"value": "RootNode"
				},
				{
					"name": "type",
					"value": "Base"
				},
				{
					"name": "blockid",
					"value": "0"
				}
			],
		},
		{
			"id": 1,
			"parent": 0,
			"data": [
				{
					"name": "id",
					"value": ""
				},
				{
					"name": "name",
					"value": "Childnode"
				},
				{
					"name": "type",
					"value": "Option"
				},
				{
					"name": "blockid",
					"value": "1"
				}
			],
		}
	]
}
```

//--------------- Its should appear like that-------------//
![image](https://user-images.githubusercontent.com/57656535/101286207-35033680-380f-11eb-8c59-0b9d90f2a945.png)
  

is it possible to it programmatically .

**Comment by juanmalunatic** [comment]
Hey @Rohitgta77 

Do you want to set up just the first block of the canvas? If so, you can just save the output of `flowy.output()` and import it when you first render Flowy.

If you want to keep adding nodes, I'd explore something like:

- Saving the current system's output with `flowy.output()` to a temporary variable
- Adding the new node to said temp variable by appending well-formed content to the three members of Flowy's output (`html`, `blockarr`, and `blocks`).
- Re-importing the temp variable using `flowy.deleteBlocks()` followed by `flowy.import(tempVar)`.

It's kind of a hassle but I that's my first though. Please let me know if you come up with a more elegant solution!

**Comment by gonzalocast17** [comment]
I would like to know if the creation of the elements can be done from programming, when starting flowy.

**Comment by Rohitgta77** [comment]
Firstly design it the block
then export the design file and save it..  
and then import it....    
......................................I do not Want Like Above...............................................



I want to make export design File ..
then import it

**Comment by Rohitgta77** [comment]
> Hey @Rohitgta77
> 
> Do you want to set up just the first block of the canvas? If so, you can just save the output of `flowy.output()` and import it when you first render Flowy.
> 
> If you want to keep adding nodes, I'd explore something like:
> 
> * Saving the current system's output with `flowy.output()` to a temporary variable
> * Adding the new node to said temp variable by appending well-formed content to the three members of Flowy's output (`html`, `blockarr`, and `blocks`).
> * Re-importing the temp variable using `flowy.deleteBlocks()` followed by `flowy.import(tempVar)`.
> 
> It's kind of a hassle but I that's my first though. Please let me know if you come up with a more elegant solution!

Firstly design it the block
then export the design file and save it..
and then import it....
......................................I do not Want Like Above...............................................

I want to make export design File ..
then import it

**Comment by gonzalocast17** [comment]
> > Hola @ Rohitgta77
> > ¿Quieres configurar solo el primer bloque del lienzo? Si es así, puede guardar la salida `flowy.output()`e importarla cuando renderice Flowy por primera vez.
> > Si desea seguir agregando nodos, exploraría algo como:
> > 
> > * Guardar la salida del sistema actual con `flowy.output()`una variable temporal
> > * Adición del nuevo nodo a dicha variable temp añadiendo contenido bien formado a los tres miembros de salida de Flowy ( `html`, `blockarr`y `blocks`).
> > * Reimportar la variable temporal usando `flowy.deleteBlocks()`seguido de `flowy.import(tempVar)`.
> > 
> > Es un poco complicado, pero es mi primera vez. ¡Por favor, avíseme si encuentra una solución más elegante!
> 
> Primero diseñe el bloque,
> luego exporte el archivo de diseño y guárdelo ...
> y luego impórtelo ....
> ........................... ........... No quiero como arriba ................................. ..............
> 
> Quiero hacer (exportar diseño) Archivo ...
> luego importarlo


I understand, but my requirement is to dynamically generate the diagram and subsequently add the elements to the diagram, that's why my need to know how to dynamically create the first instance elements. Do you know how to do it? Is it possible?

**Comment by Rohitgta77** [comment]
> > > Hola @ Rohitgta77
> > > ¿Quieres configurar solo el primer bloque del lienzo? Si es así, puede guardar la salida `flowy.output()`e importarla cuando renderice Flowy por primera vez.
> > > Si desea seguir agregando nodos, exploraría algo como:
> > > 
> > > * Guardar la salida del sistema actual con `flowy.output()`una variable temporal
> > > * Adición del nuevo nodo a dicha variable temp añadiendo contenido bien formado a los tres miembros de salida de Flowy ( `html`, `blockarr`y `blocks`).
> > > * Reimportar la variable temporal usando `flowy.deleteBlocks()`seguido de `flowy.import(tempVar)`.
> > > 
> > > Es un poco complicado, pero es mi primera vez. ¡Por favor, avíseme si encuentra una solución más elegante!
> > 
> > 
> > Primero diseñe el bloque,
> > luego exporte el archivo de diseño y guárdelo ...
> > y luego impórtelo ....
> > ........................... ........... No quiero como arriba ................................. ..............
> > Quiero hacer (exportar diseño) Archivo ...
> > luego importarlo
> 
> I understand, but my requirement is to dynamically generate the diagram and subsequently add the elements to the diagram, that's why my need to know how to dynamically create the first instance elements. Do you know how to do it? Is it possible?
> ...
> or maybe I don't understand what you mean by the comment above

I was replied to juanmalunatic... its not for you ....

**Comment by Rohitgta77** [comment]
> > > Hola @ Rohitgta77
> > > ¿Quieres configurar solo el primer bloque del lienzo? Si es así, puede guardar la salida `flowy.output()`e importarla cuando renderice Flowy por primera vez.
> > > Si desea seguir agregando nodos, exploraría algo como:
> > > 
> > > * Guardar la salida del sistema actual con `flowy.output()`una variable temporal
> > > * Adición del nuevo nodo a dicha variable temp añadiendo contenido bien formado a los tres miembros de salida de Flowy ( `html`, `blockarr`y `blocks`).
> > > * Reimportar la variable temporal usando `flowy.deleteBlocks()`seguido de `flowy.import(tempVar)`.
> > > 
> > > Es un poco complicado, pero es mi primera vez. ¡Por favor, avíseme si encuentra una solución más elegante!
> > 
> > 
> > Primero diseñe el bloque,
> > luego exporte el archivo de diseño y guárdelo ...
> > y luego impórtelo ....
> > ........................... ........... No quiero como arriba ................................. ..............
> > Quiero hacer (exportar diseño) Archivo ...
> > luego importarlo
> 
> I understand, but my requirement is to dynamically generate the diagram and subsequently add the elements to the diagram, that's why my need to know how to dynamically create the first instance elements. Do you know how to do it? Is it possible?
> ...
> or maybe I don't understand what you mean by the comment above

And I am also asking question for dynamic design to owner..

**Comment by alyssaxuu** [comment]
Hey, you can't currently create blocks programmatically with Flowy. This is because there is no established design (there is in the demo, but it's just for demonstration purposes). You can first make the tree yourself, export it using flowy.output(), and save this information to re-draw the tree programmatically with flowy.import().

**Comment by Rohitgta77** [comment]
> Hey, you can't currently create blocks programmatically with Flowy. This is because there is no established design (there is in the demo, but it's just for demonstration purposes). You can first make the tree yourself, export it using flowy.output(), and save this information to re-draw the tree programmatically with flowy.import().
====
Okay .. there are no way to create blocks programmatically..
=====

**Comment by gonzalocast17** [comment]
> Oye, actualmente no puedes crear bloques mediante programación con Flowy. Esto se debe a que no hay un diseño establecido (lo hay en la demostración, pero es solo para fines de demostración). Primero puede crear el árbol usted mismo, exportarlo usando flowy.output () y guardar esta información para volver a dibujar el árbol programáticamente con flowy.import ().



> Oye, actualmente no puedes crear bloques mediante programación con Flowy. Esto se debe a que no hay un diseño establecido (lo hay en la demostración, pero es solo para fines de demostración). Primero puede crear el árbol usted mismo, exportarlo usando flowy.output () y guardar esta información para volver a dibujar el árbol programáticamente con flowy.import ().


create the tree you mean draw the whole diagram and then export it?

**Comment by alyssaxuu** [comment]
> > Oye, actualmente no puedes crear bloques mediante programación con Flowy. Esto se debe a que no hay un diseño establecido (lo hay en la demostración, pero es solo para fines de demostración). Primero puede crear el árbol usted mismo, exportarlo usando flowy.output () y guardar esta información para volver a dibujar el árbol programáticamente con flowy.import ().
> 
> > Oye, actualmente no puedes crear bloques mediante programación con Flowy. Esto se debe a que no hay un diseño establecido (lo hay en la demostración, pero es solo para fines de demostración). Primero puede crear el árbol usted mismo, exportarlo usando flowy.output () y guardar esta información para volver a dibujar el árbol programáticamente con flowy.import ().
> 
> create the tree you mean draw the whole diagram and then export it?

Yes, you can draw the diagram and save it to import it programmatically.

**Comment by gonzalocast17** [comment]
> > > Oye, actualmente no puedes crear bloques mediante programación con Flowy. Esto se debe a que no hay un diseño establecido (lo hay en la demostración, pero es solo para fines de demostración). Primero puede crear el árbol usted mismo, exportarlo usando flowy.output () y guardar esta información para volver a dibujar el árbol programáticamente con flowy.import ().
> > 
> > 
> > > Oye, actualmente no puedes crear bloques mediante programación con Flowy. Esto se debe a que no hay un diseño establecido (lo hay en la demostración, pero es solo para fines de demostración). Primero puede crear el árbol usted mismo, exportarlo usando flowy.output () y guardar esta información para volver a dibujar el árbol programáticamente con flowy.import ().
> > 
> > 
> > crear el árbol, ¿te refieres a dibujar todo el diagrama y luego exportarlo?
> 
> Sí, puede dibujar el diagrama y guardarlo para importarlo mediante programación.

Ok thank you very much hope and soon we can add blocks programmatically, regards.

**Comment by wscjxky** [comment]
Thank all of you very much for sharing 👍

I tried many ways to build flow through nodes, none of them worked very well. 😟😟😟

SO I developed a set of functions for **automatic programmatically adding nodes** implemented based on simulated drag and drop
, hoping to help someone.


- First I would create a node json string
```
let NODE_RELATION = {
        root: [{
            "type": "gongwei",
            "name": "gongwei_1",
            "parent_id": -1,
            "children": [{
                "parent_id": 1,
                "type": "pipeline",
                "name": "pipeline_1",
                "children": [{
                    "type": "analyze",
                    "name": "analyze_1",
                    "parent_id": 3,
                    "children": []
                }]

            }]
        }, {
            "parent_id": -1,
            "type": "gongwei",
            "name": "gongwei_2",
            "children": []
        }]
    }
```

- In the second part🚗🚗🚗, I will create a function that adds nodes. In this function, the mousedown function will be used, and then the **flowy.drag** object will be dynamically modified to move the object's position to the middle of the screen.
- It should be noted that offset and px will change according to the screen size.

```

    function add_node(node_type, node_name, parent_node_id) {
        offset_y = 35
        offset_x = 200

        $(`#${node_type}`).click()

        let evt = new MouseEvent("mousedown", {
            bubbles: true,
            cancelable: true,
            view: window,
        });
 

        $(`input[value="${node_name}"]`).parent()[0].dispatchEvent(evt);
        console.log('flowy.drag()', flowy.drag())
        if (parent_node_id == -1) {
            flowy.drag().style.left = '900px'
            flowy.drag().style.top = '150px'
        } else {
            flowy.drag().style.left = flowy.blocks()[parent_node_id].x + offset_x + "px"
            flowy.drag().style.top = flowy.blocks()[parent_node_id].y + offset_y + "px"
        }

        let evt1 = new MouseEvent("mouseup", {
            bubbles: true,
            cancelable: true,
            view: window,
        });
        $('#canvas')[0].dispatchEvent(evt1);
    }

```

- Finally, the final flowy can be constructed by traversing the data json according to the number of layers.

```
add_node('root', 'root', -1)
for (let level_1 of NODE_RELATION['root']) {
    add_node(level_1['type'], level_1['name'], level_1['parent_id'])
}

```




- If you need all the codes you can contact me ❤❤❤


![image](https://github.com/alyssaxuu/flowy/assets/21272297/d91ebe13-5a3c-43cd-936a-9d49faac9307)
