### ISSUE TITLE
rearranging blocks on canvas disturbe style

### ISSUE THREAD

**Issue by er-chaan** [alyssaxuu/flowy#112]
steps to reproduce
- make a tree with (A parent with child B,C)
- add grand child D to node B
- rearrange child D to node C
- add new child E to node D (it will break css)

![Screenshot_2020-12-16](https://user-images.githubusercontent.com/30405755/102341177-763cd880-3fbd-11eb-8eb4-33788ef2b3c6.png)

**Comment by er-chaan** [comment]
after doing r&d with canvas properties and style.css issue sorted

**Comment by juanmalunatic** [comment]
Hey @er-chaan,

Could you share which solution worked for you? I remember having this same issue on & off

**Comment by sureshmatsio** [comment]
For anyone encountering the same issue this is what worked for me. 

In the js file line 328 i removed the absy variable. Not sure if it was required or not but it is what worked for me.

Replaced line 328 with the line given below.

blockstemp.filter(a => a.id == parseInt(drag.querySelector(".blockid").value))[0].y = (drag.getBoundingClientRect().top + window.scrollY) + (parseInt(window.getComputedStyle(drag).height) / 2) + canvas_div.scrollTop - canvas_div.getBoundingClientRect().top;

**Comment by alyssaxuu** [comment]
> For anyone encountering the same issue this is what worked for me.
> 
> In the js file line 328 i removed the absy variable. Not sure if it was required or not but it is what worked for me.
> 
> Replaced line 328 with the line given below.
> 
> blockstemp.filter(a => a.id == parseInt(drag.querySelector(".blockid").value))[0].y = (drag.getBoundingClientRect().top + window.scrollY) + (parseInt(window.getComputedStyle(drag).height) / 2) + canvas_div.scrollTop - canvas_div.getBoundingClientRect().top;

Oops, yes, the absy variable isn't supposed to go there (it's used for offsets in the x/y positions in the DOM, but not when storing the data). Just updated it, should be fine now.
