### ISSUE TITLE
Bug: dragging repeatedly makes the arrows drift away from the block

### ISSUE THREAD

**Issue by juanmalunatic** [alyssaxuu/flowy#115]
When you drag a block repeatedly, the connecting arrows start moving away from their original position. To reproduce, go to the demo (https://alyssax.com/x/flowy/) and link two blocks. Now, drag the parent a minuscule amount several times. 

Video:
![flowy_arrows](https://user-images.githubusercontent.com/18034970/106201946-386bcc00-6187-11eb-96b2-fc08bf162b14.png)

**Comment by alyssaxuu** [comment]
Oops, the code in the live demo wasn't up to date with the codebase. It should work fine now :)
