### ISSUE TITLE
Get data from data attributes

### ISSUE THREAD

**Issue by JoFont** [alyssaxuu/flowy#14]
Suggestion: It would be nice to be able to get reference to all data attributes within the context of a `create-flowy` container. This would highly improve the possibilities of custom logic with the output

Also, as I see it now, data from inputs is only working for the container's root level inputs, would be nice if it would instead traverse the container's tree and find all nested inputs. This would eliminate current styling limitations.

Thank you very much! :)

**Comment by alyssaxuu** [comment]
I'm going to look into having the data attributes outputted as well, should be useful.

Hm, so you mean to say that if there's an input nested inside say a div within the `create-flowy` container it won't show up? That's odd if so, I'll have to fix it for sure.

**Comment by JoFont** [comment]
Yes, thank you! Made a pull request with a fix, you're using .children() on the output which only travels one level. Changed to .find() which will traverse the container.

**Comment by alyssaxuu** [comment]
Fixed the issue to get all nested inputs & added data attributes to the output.
