### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by theklr** [alyssaxuu/flowy#144]
Just wanted to check in to see if this is getting support or any plans of support in the near future

**Comment by alyssaxuu** [comment]
Sorry, I haven't been able to dedicate myself to this library as my current focus is on [Screenity](https://github.com/alyssaxuu/screenity). My plan was at some point to rewrite Flowy to work better and have more features, but I don't currently have the time sadly. I can't really make any promises at this point.

**Comment by theklr** [comment]
No problem, thanks for the update
