### ISSUE TITLE
Semantic Versionning flowy

### ISSUE THREAD

**Issue by benjaminaudet** [alyssaxuu/flowy#17]
I'm currently trying to run locally the project on my PC in order to contribute.
The thing is, I have a bug when I try to link a block to another on the demo project and the error comes from flowy.js itself (line 364 if you wondering).

I assume that the current live demo isn't running on the last master's commit but I'm not able to check it myself since the flowy.js is not signed with a header that could allow us to check the version of the file.

What do you think about beginning to do that?

**Comment by alyssaxuu** [comment]
Already fixed the issue, I wasn't keeping the demo folder up to date ^^
