### ISSUE TITLE
Flowy broken since 7 days

### ISSUE THREAD

**Issue by benjaminaudet** [alyssaxuu/flowy#18]
As I said in the issue #17 I have a bug, but I create that issue because I want it to be independant bug report.

Since the commit `600edfcbbf890a6529dd6cee43c957daf6693fc6` the demo isn't working anymore as the live demo shows it.
When I try to link a block with another and interact with the first one after that, it makes an error in the console : 
![image](https://user-images.githubusercontent.com/9674694/70414713-2c8cea00-1a5b-11ea-9dca-49b34a2fcd01.png)
This error come from the line 364, basically it crashes because the array blackstemp that you're filtering have one undefined element in it.

It works fine before the commit `600edfcbbf890a6529dd6cee43c957daf6693fc6`.

**Comment by benjaminaudet** [comment]
After some investigating, looks like this part of the commit on the file flowy.js that makes the error appears :
![image](https://user-images.githubusercontent.com/9674694/70415850-dff6de00-1a5d-11ea-80c2-30bd23be68c8.png)

**Comment by alyssaxuu** [comment]
I assume you're talking about the demo in the demo folder - I checked and indeed it had a bug which I've just fixed. I've tried to recreate the issue but couldn't, it seems to work fine for snapping and interacting and rearranging.
