### ISSUE TITLE
style issue while lifting block

### ISSUE THREAD

**Issue by crapthings** [alyssaxuu/flowy#19]
normal

![image](https://user-images.githubusercontent.com/1147704/70506302-ecb22980-1b64-11ea-86ec-2ba48c4f991a.png)

onDrag

![image](https://user-images.githubusercontent.com/1147704/70506316-f2a80a80-1b64-11ea-8a9d-7b4b8687997f.png)

the padding broke

**Comment by alyssaxuu** [comment]
Fixed
