### ISSUE TITLE
Unusable mobile view (iPhone X)

### ISSUE THREAD

**Issue by rschindhelm** [alyssaxuu/flowy#21]
Congrats on the Smashing Magazine feature.

I wanted to try the tool on my iPhone X, but the canvas is barely visible, and I couldn't maximize it by collapsing the menu. Am I missing something?

**Comment by alyssaxuu** [comment]
The demo isn't really optimized for mobile, but I suppose I could try to make it work better for that. Indeed the sidebar can't be collapsed, I know I added a button there which is a bit stupid, but I wanted to make sure people didn't randomly close the sidebar and be confused as to where to get the blocks.

I could add that tiny functionality though, it's honestly not a big deal and a bit of an oversight from my part.

**Comment by alyssaxuu** [comment]
Closing this issue as even if the panel did collapse, the user then would be unable to drag the blocks onto the canvas. Might explore another way to implement this eventually - but ultimately it is not a problem of the library, rather how it is implemented (and furthermore a mobile-friendly solution could be thought out by the developer).
