### ISSUE TITLE
Strange behaviour when dettaching children element

### ISSUE THREAD

**Issue by koas** [alyssaxuu/flowy#26]
How to reproduce: drop an element, then drop another element as a child, then a third one as child of the second one, now we hace three connected elements.

Now dettach the second element from the first one by moving it away from the parent. The 2nd and 3rd elements disappear when you release the mouse button. This seemed a bit strange to me, I was expecting those two elements to remain connected and on screen, just independent from the first element.

But the real problem is that form this point on you can't drop another element. You can drag it to the canvas, but upon releasing the mouse button the element stays "glued" to the cursor.

[Here's a video of this behaviour](https://youtu.be/q59DrA5hZag)

**Comment by alyssaxuu** [comment]
Just fixed it - was a small issue with the blue indicator block getting accidentally deleted and thus triggering a javascript error.

As per the blocks getting removed, I've currently kept it that way for simplicity, with only one tree, although if there's a lot of interest I could allow for multiple trees. Shouldn't be hard to implement, but it would lead to having blocks that overlap, making it harder to snap new blocks or to rearrange them.

**Comment by koas** [comment]
Thanks a lot for the quick fix!

**Comment by johndkn** [comment]
> As per the blocks getting removed, I've currently kept it that way for simplicity

When a block is detached from all blocks, is it possible to snap it back to the previous parent instead of removing it ?

Because when I click on the header (or on the 3 dots in the block header), my mouse often move just a little bit, and the block is suddenly removed.

Or maybe add a threshold distance value above which the block is removed ?
