### ISSUE TITLE
Submenu item disabled

### ISSUE THREAD

**Issue by fqure** [alyssaxuu/flowy#27]
Wasn't sure if this was intended in demo but the submenu toggle item _Triggers_ becomes permanently disabled (class .navdisabled) once the other items _Actions, Loggers_ are selected (class .navactive).

**Comment by alyssaxuu** [comment]
Fixed!

**Comment by fqure** [comment]
Fast! 
...
Also, your [online demo](https://alyssax.com/x/flowy/) needs to update

**Comment by alyssaxuu** [comment]
Works for me - maybe you have to clear the cache?
