### ISSUE TITLE
How to present conditional and looping with flowy?

### ISSUE THREAD

**Issue by kafai97** [alyssaxuu/flowy#28]
Hi, I would like to create a flowchart tool with flowy to describe the program process. Then I got 2 problems about how to initiate arrows between blocks:
1. Conditional statement: suppose there was an if-else statement and 2 branches were created, then the subsequent blocks were not able to be merged into one since one block with 2 parents is not allowed.
2. Looping: similar problem. Is it possible to represent a loop with Flowy?

Maybe it was hard to have a clear description only with words. For example, is Flowy able to describe the following flowchart?
![](https://cacoo.com/assets/site/img/examples/flowchart-hero-right.png)

**Comment by alyssaxuu** [comment]
Currently Flowy doesn't have such features as it's meant to be minimal. Could implement those if I could think of a simple user behaviour to make such connections - would the blocks automatically come with that sort of logic (e.g. the Validate block loop, or in the case of if/else)? Are there only specific scenarios where this would happen or should it be possible to generate connections between blocks as needed?

**Comment by sfmskywalker** [comment]
I discovered this amazing project just 5 minutes ago, but I'm already considering replacing my [Elsa Workflow designer](https://github.com/elsa-workflows/elsa-designer) (which is based on [jsPlumb](https://jsplumbtoolkit.com/)) with Flowy.

However, as @kafai97 describes, I'm looking for the ability to allow arbitrary connections be made between any two blocks. This enables modeling flowcharts to loop back, fork/join and multiple incoming connections to a given block as depicted here:

![](https://miro.medium.com/max/1500/1*Gn6TCvN2iQYpgsPrUEl1jQ.png)

From what I've seen so far, Flowy automatically creates a connection when dropping a block from the toolbox onto another block on the canvas.

Perhaps the following UX could help:

1. User drops a block A onto the canvas.
1. User drops another block B onto the canvas (not on block A, but below/besides/arbitrary location).
1. Now the user wants to connect the two blocks manually. They do so by clicking/hovering the source block, after which available endoints (the little blue circles) appear. User grabs one of these endpoints and drags it onto the target block. A new connection is created after releasing the mouse.

It would work a little bit like this [demonstration](https://lively-kernel.org/repository/webwerkstatt/users/tmohr/libs/jsPlumb/demo/jquery/flowchartConnectorsDemo.html).

In the case of the designer requirements for Elsa Workflows, I would need the designer to allow each block to have an arbitrary number of handles/endpoints from which the user can drag connections to other blocks.

I guess the tricky part might be the automatic layout of blocks that you have currently in place. I noticed that as soon as I drop a block onto another block, a connection is automatically created and the block is automatically given a location on the canvas. I imagine you perform this layout based on blocks and their connections. When you were to allow users to drop blocks without having a connection initially, it would probably be difficult to determine where the block should be located. On the other hand, perhaps it makes sense for disconnected blocks to not be auto-positioned at all, and just let them "float" - until the user connects this block to another one, after which Flowy would perform the automatic layout.

Is this something you would consider implementing?

**Comment by alyssaxuu** [comment]
> I discovered this amazing project just 5 minutes ago, and I'm already considering replacing my [Elsa Workflow designer](https://github.com/elsa-workflows/elsa-designer) (which is based on [jsPlumb](https://jsplumbtoolkit.com/)) with Flowy.
> 
> However, as @kafai97 describes, I'm looking for the ability to allow arbitrary connections be made between any two blocks. This enables modeling flowcharts to loop back, fork/join and multiple incoming connections to a given block as depicted here:
> 
> ![](https://camo.githubusercontent.com/94b4d566e22d41381235e62c3e9195427684b8b4/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313530302f312a476e365443764e32695159706773507255456c316a512e706e67)
> 
> From what I've seen so far, Flowy automatically creates a connection when dropping a block from the toolbox onto another block on the canvas.
> 
> Perhaps the following UX could help:
> 
> 1. User drops a block A onto the canvas.
> 2. User drops another block B onto the canvas (not on block A, but below/besides/arbitrary location).
> 3. Now the user wants to connect the two blocks manually. They do so by clicking/hovering the source block, after which available endoints (the little blue circles) appear. User grabs one of these endpoints and drags it onto the target block. A new connection is created after releasing the mouse.
> 
> It would work a little bit like this [demonstration](https://lively-kernel.org/repository/webwerkstatt/users/tmohr/libs/jsPlumb/demo/jquery/flowchartConnectorsDemo.html).
> 
> In the case of the designer requirements for Elsa Workflows, I would need the designer to allow each block to have an arbitrary number of handles/endpoints from which the user can drag connections to other blocks.
> 
> I guess the tricky part might be the automatic layout of blocks that you have currently in place. I noticed that as soon as I drop a block onto another block, a connection is automatically created and the block is automatically given a location on the canvas. I imagine you perform this layout based on blocks and their connections. When you were to allow users to drop blocks without having a connection initially, it would probably be difficult to determine where the block should be located. On the other hand, perhaps it makes sense for disconnected blocks to not be auto-positioned at all, and just let them "float" - until the user connects this block to another one, after which Flowy would perform the automatic layout.
> 
> Is this something you would consider implementing?

I understand the need for this sort of functionality in some scenarios, but I just feel like this is not what this library is really about. I created this because all the other flowchart libraries were unnecessarily complicated, made it hard to place blocks which you then had to connect manually, and often required other dependencies like jQuery.

Flowy is just a simple library that allows people to quickly implement flowchart functionality in their projects with basic features, with very few lines of code. People are free to add more functionality to the library depending on their needs, but I like the base being as simple as possible, with only the most important features coming together with it.

What you are proposing is basically just turning this into a complex flowchart library, and having the same functionality that many other Javascript libraries already have - nothing unique about that. I don't really plan to do so, and in any case, it would be something separate from Flowy, most certainly.

**Comment by alyssaxuu** [comment]
I'm closing this issue as it deviates too much from the current library, and I can't think of any possible implementations that would work with it in the current state.
