### ISSUE TITLE
Conditional snap / connection

### ISSUE THREAD

**Issue by unruledboy** [alyssaxuu/flowy#3]
Hi,

In real life usage, a block may/may not be able to connect to another block due to biz requirements.

I notice there is "onSnap()" function, best bet may have built-in support to determine the snap is allowed or not based on some rules. 

Alternatively, provide the ability to cancel the snap by exposing source/target blocks would help.

**Comment by jerivas** [comment]
A `beforeSnap` callback might be useful, it could return a boolean to allow / deny a snap

**Comment by alyssaxuu** [comment]
That could certainly be added in. Probably being able to see the data from the parent block it would be attaching to so you can create a condition based on that. Should the block automatically delete itself though if it can't be attached, or should that be up to how you want to implement it (for example, moving the block elsewhere instead or any other sort of behaviour)?

**Comment by unruledboy** [comment]
@alyssaxuu a better option maybe: still keep the bock, just not auto snap, and bold border highlights in red indicating it is not applicable, potentially showing additional info to explain why it cannot be auto snap.

**Comment by alyssaxuu** [comment]
In that case I could just allow people to customize the behaviour themselves, simply not deleting by default (so you can outline for example, add more info, delete if you want, etc.). I want to keep it as versatile as possible so I think that would be the best way to go about it.

**Comment by alyssaxuu** [comment]
Implemented the conditional snap behaviour.
