### ISSUE TITLE
Blocks don't snap correctly after flowchart becomes large in size (blocks do not update positions correctly)

### ISSUE THREAD

**Issue by nicoladaoud** [alyssaxuu/flowy#31]
Hello Alyssa X,
Thanks for the awesome work. 

I was testing out Flowy, and I noticed that after the flowchart becomes relatively large, Flowy is unable to correctly snap the dragged block with the intended block. I noticed that this issue happens when you start scrolling back and forth (usually horizontally). 
For example, try attaching 12 children to one parent block, and you will notice that the dragged block will not correctly determine its position with the block you are trying to snap it to. (assuming you scroll right to try and attach to parent block.)

once you start scrolling back and forth the blocks position does not update correctly.

I think the problem is with window.scrollX and window.scrollY. I tried changing them to canvas_div.scrollX but it would not work. I also tried changing some of the style as overflow attribute could cause some problems. I was using chrome if it matters. I was not able to fix this problem and spent a lot of time trying to fix it.
Any help is greatly appreciated!
Thank you

**Comment by nicoladaoud** [comment]
did anybody figure out a way to fix this?

**Comment by alyssaxuu** [comment]
I'm going to look into this! Indeed there's an issue and it has to do with the scrollX of the canvas itself. Could have been caused after I removed jQuery from the library, since there often isn't a direct equivalent of expressions in ES6. Full priority on this one!

**Comment by alyssaxuu** [comment]
Fixed, indeed it was due to removing jQuery. In some parts I was using scrollX/Y instead of scrollLeft/Top. Should be working fine now!
