### ISSUE TITLE
Custom action when dettaching children element

### ISSUE THREAD

**Issue by johndkn** [alyssaxuu/flowy#32]
Following up on #26 :

> As per the blocks getting removed, I've currently kept it that way for simplicity

Would it be possible to override the default behaviour in the "onRelease()" function ? Or in a new "onRemoveSnap()" function ?

Use cases :
- If we want to display an alert (asking for confirmation) before removing the block (and its children) ?
- If we want to snap it back to the previous block instead of removing it ?
- If we want to trigger custom actions (e.g. save in database) before and/or after a block (and its children) are removed.

**Comment by johndkn** [comment]
Maybe is it possible to define/override the default behaviour in the onRelease() function ?

For example : 
- if we want to snap it back to the previous block instead of removing it ?
- if we want to display an alert before removing the block and its children ?

**Comment by alyssaxuu** [comment]
That's a good point. I should probably add this functionality - although I was thinking about tackling this when (or if) I add multiple tree functionality, as that might be the desired outcome when you de-attach a block & drop it somewhere. Problem is that adding multiple tree functionality is a bit complicated when the blocks overlap (I could automatically "space the trees out" when you drop the block(s) but the user might be confused if when they release the block it moves miles away), as then when it comes to snapping (the blue dot that shows when you're close) there might be multiple blocks that could meet the criteria and "break" the engine.

All in all, definitely something that's in my mind, but I think considering I have "plans" to add multiple trees it doesn't make much sense currently to allow for custom actions when deattaching children blocks.

**Comment by johndkn** [comment]
Thanks for your reply :)

I understand you want to wait for the multiple tree functionality to add this feature. 

In the meantime, is there a way for me (with the current methods) to add a "confirmation alert" before removing a detached element ?

Because I often unintentionally detach blocks by slightly moving them (a few pixels) when trying to open the "Property panel". And then, I have to rebuild the tree again...

**Comment by fbennets** [comment]
First, thanks for this awesome library and great demo, @alyssaxuu!

I encountered the same problem and built a custom solution, which requires a slight modification of the library. The explanation is pretty long, see here https://open-decision.herokuapp.com/visualbuilder for a working demo, all customised/edited blocks are saved and shown in the blocklist. Use 'test' as user and 'demo1234' as password. 

This is the [modified library ](https://github.com/fbennets/open-decision/blob/production/static/flowy/flowy.js) and the [implementation](https://github.com/fbennets/open-decision/blob/production/visualbuilder/templates/visualbuilder.html).

@alyssaxuu I you want me to, I could try to refactor my code, built a decent "deleted"-handler for the library and create a PR?
____

I added a new argument "deleted" in line 1
`var flowy = function(canvas, grab, release, snapping, deleted, spacing_x, spacing_y)`
a default after line 12

`  if (!deleted) {
        deleted = function() {};
    }
`

After line 404 I catch the detached block and make sure it is not the starter block (which has the blockid 0) and pass the detached element as well as the blocks array
`              if (drag.querySelector(".blockid").value !==  "0"){
                              blockDeleted(drag, blocks);
                            }
`
And than added the callback after line 568

```
function blockDeleted(block, blockList) {
        deleted(block, blockList)
```

In your main.js you then need to pass a callback. I allow the user to set some data for the blocks in the property sidebar, this data is saved in serialized JS-Object as textContent of a div with the id "storage-div" that is attached as a child of the blockelem-div after the blockinfo-div. Interestingly, the dragged/distached block contains the data of all its child blocks at the moment I catch it with the handler above. Therefore I can simply use a regex to get a list of the parent and all child blocks after they have been detached. I store the data of this blocks in the global array  

```
        function deleted(draggedBlock, blockList) {
          nodes = draggedBlock.innerHTML.match(/{.+?}/gm);
          if (nodes !== null) {
            detachedBlocks.push(nodes);
          }
```

In the next step I need to check if the blocks have only been detached and reattached or if they have been deleted.  I trigger the function with the release handler.

```
function release() {
          if (detachedBlocks.length !== 0){
            checkdetachedBlocks();
          };
            tempblock2.classList.remove("blockdisabled");
        }
```
Here I check if the blocks in detachedBlocks are still present in the canvas (if they have been reattached) or if they have been deleted. If they have been deleted, I store them in the deleted blocks array.

```
    function checkDetachedBlocks(...args){
      releaseCounter += 1;
      len = detachedBlocks.length;

      //If  release is called directly after releasing the blocks,
      //the new blocks are not available in the  canvas, therefore wait until 2nd call
      if ((len !== 0 )&& (releaseCounter == 2)) {

        //Get all existing nodes with a storage-div
        var existingBlocks = document.getElementById('canvas').querySelectorAll("#storage-div");

        //We get the id and name of the older block (the name is one of the properties the user can set)
            var tempDelBlockId = ((detachedBlocks[0].constructor === Array)
                                  ? JSON.parse(detachedBlocks[0][0]).blockId
                                  : JSON.parse(detachedBlocks[0]).blockId);

            var tempDelBlockName = ((detachedBlocks[0].constructor === Array)
                                  ? JSON.parse(detachedBlocks[0][0]).inputValues[0]
                                  : JSON.parse(detachedBlocks[0]).inputValues[0]);

          //Compare the id of existing blocks and the deleted block if they match, the blocks were not
          //deleted but only moved -> then remove block from deletedBlocks
          var blockWasDeleted = true;
        for (var i=0; i<existingBlocks.length; i++){
          if ((JSON.parse(existingBlocks[i].textContent).inputValues[0] == tempDelBlockName) && (JSON.parse(existingBlocks[i].textContent).blockId == tempDelBlockId)){

            //Remove block from deleted blocks
            detachedBlocks.splice(-2, 1);
            blockWasDeleted = false;
          }
        }
        if (blockWasDeleted) {

          //Check if several blocks were deleted at once (if we have a multidimensional array)
          if (detachedBlocks[0].constructor === Array){

            //If multidimensional array, push single blocks to deletedBlocks
            for (var j=detachedBlocks[0].length-1; j >= 0; j--){
              deletedBlocks.push(detachedBlocks[0].pop());
            }

            //Then delete the empty array in detachedBlocks that contained the blocks
            detachedBlocks.shift();
          } else {

            //If only one block was deleted push it to deletedBlocks
            deletedBlocks.push(detachedBlocks.shift())
          }
        }

        //If detachedBlocks.length was originally 2 one block is left. As we only
        //want one or two blocks in the array for predictability, set releaseCounter to one
        releaseCounter = (len == 2) ? 1 : 0;
  }
}
```
Then I generate a blocklist from the deletedBlocks and show them in the Blocklist.

```
function showDeletedBlocks(){
  if (detachedBlocks.length !== 0 ){
    checkDetachedBlocks();
  }
  blockList = '';
  if (deletedBlocks.length !== 0){
  for (var i=0; i<deletedBlocks.length; i++) {
    el = JSON.parse(deletedBlocks[i]);
    blockList += `<div class="blockelem create-flowy noselect"><input type="hidden" name="blockelemtype" class="blockelemtype" value=${20+i}><div class="grabme"><img src="{% static 'flowy/assets/grabme.svg' %}"></div><div class="blockin"><div class="blockico"><span></span><img src="{% static 'flowy/assets/eye.svg' %}"></div><div class="blocktext"><p class="blocktitle">Deleted Block</p><p class="blockdesc">${el.inputValues[0]}</p></div></div></div><div class="finaldelete" data-id=${20+i}>Delete</div>`
  }
} else {
  blockList += '<p>You have no deleted nodes.</p>'
}
  return blockList
}
```

**Comment by johndkn** [comment]
Wow, this is great! thanks @fbennets! 
@alyssaxuu that would be awesome to have a pull request with this deleted handler

**Comment by alyssaxuu** [comment]
Added a new method to add this functionality.
