### ISSUE TITLE
Add copy-paste-able tags to README?

### ISSUE THREAD

**Issue by hchiam** [alyssaxuu/flowy#34]
It'd be nice to give people the convenient option to copy-paste CDN links into their HTML: 

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/alyssaxuu/flowy@master/flowy.min.css"></link>
```

and

```html
<script src="https://cdn.jsdelivr.net/gh/alyssaxuu/flowy@master/flowy.min.js"></script>
```

and then if you make a [release](https://github.com/alyssaxuu/flowy/releases) you can change the `@master` to something like `@1.0.0` so the code stays stable on websites that use it, even when updates are made to those files in this repo.

I'm also working on a minimal demo: https://codepen.io/hchiam/pen/qBEogMR

**Comment by alyssaxuu** [comment]
Added.
