### ISSUE TITLE
Dragging problem after importing data

### ISSUE THREAD

**Issue by emoreno108** [alyssaxuu/flowy#35]
Hello Alyssa: Congrat and thanks!!!! for your great plugin, I think best of this kind. I´m checking it and I got a problem with the drag performing after flowy. importing data: Data is displayed well but drag stopped working, I mean, when you click on an object this remains stocked in the mouse cursor and never is released. This issue happens under only one condition: on importing after start the page. I recycle output->import and works fine, I publish to database and read it rightaway and works fine, only happens when I restart and import the data from database. it is not a parsing problem, I tryed with a flowy.output string constant as data and when it is imported after page start the fails come out. Message in console is:  TypeError: tempblock2 is undefined. You use two functions in main.js drag(block) and release() I "consoled" them inside with some text, and the problem is drag(block) never runs. I reclarify: this issue only happens after reloading the page and flowy.import data. Thanks in advance Alyssa for your help.

**Comment by emoreno108** [comment]
Update: Something interesting. If I drag&drop a new block inside canvas after reloading the page and then I import the database data, dragging works well, no drag problem. But a new block has to be dropped first. My idea is just to read data from database after reloading so that user can edit his (her) flowchart. Do you have which var can be set before fisrt importing to avoid the issue? Thanks a lot Alyssa, my Best Regards

**Comment by robhoward** [comment]
if you are building off the demo you'll need to change release() to check if tempblock2 is truthy. When imported it doesn't get set.

**Comment by imeneses** [comment]
I am having the exact same issue. Did anyone find a solution for this? Any help would be greatly appreciated.

**Comment by alyssaxuu** [comment]
Just fixed it.

**Comment by imeneses** [comment]
Hi Alyssa, thank you so much for addressing this bug. I still get the following error: Uncaught TypeError: Cannot read property 'parentNode' of null
    at snapping (main.js:15)
    at blockSnap (flowy.js:566)
    at HTMLDocument.flowy.endDrag (flowy.js:155)

**Comment by alyssaxuu** [comment]
> Hi Alyssa, thank you so much for addressing this bug. I still get the following error: Uncaught TypeError: Cannot read property 'parentNode' of null
> at snapping (main.js:15)
> at blockSnap (flowy.js:566)
> at HTMLDocument.flowy.endDrag (flowy.js:155)

Are you building straight from the demo, or have you customized / made your own version out of it? Keep in mind the main.js file is meant to be an implementation of the library meant specifically for the demo, so it works with the sort of setup I am using. For example in the line where your error is being thrown out, it is  simply removing the little dots on the left of the cards that represent that they can be dragged, so if in your version you aren't using those, it's not going to be compatible.

**Comment by imeneses** [comment]
I am using your demo out of the box since I started customizing and getting errors so I wanted to make sure they weren't caused by my changes. The flowchart loads fine, the error happens when I try to either add another block or move an existing one.

**Comment by alyssaxuu** [comment]
> I am using your demo out of the box since I started customizing and getting errors so I wanted to make sure they weren't caused by my changes. The flowchart loads fine, the error happens when I try to either add another block or move an existing one.

Right, so this is after importing the flowchart data I assume?

**Comment by imeneses** [comment]
Yes, it imports fine but if I drag any existing block or try to add another one it behaves weird, like the parent block isn't snapping

**Comment by alyssaxuu** [comment]
> Yes, it imports fine but if I drag any existing block or try to add another one it behaves weird, like the parent block isn't snapping

That's really odd, I've just tried it and it works fine for me. Maybe you can share the sort of flowchart you're exporting/importing? I just added a parent with a child and I had no problem rearranging or dragging new blocks in.
