### ISSUE TITLE
Incorrect offset calculation in drag begin resulting in large gap between mouse pointer and draggable clone

### ISSUE THREAD

**Issue by codding-buddha** [alyssaxuu/flowy#36]
In flowy.beginDrag offset calculation is resulting in incorrect behavior in a scenario where the editor is positioned inside an absolutely positioned container. Offset calculated here is relative to parent node here whereas it should be relative to the document, because of this in such scenarios there is a large gap between draggable clone and mouse pointer.

**Comment by abasse** [comment]
I have the same issue. Any ideas how to fix it?

**Comment by alyssaxuu** [comment]
Should be fixed now, I made it relative to the document instead of the parent.
