### ISSUE TITLE
Initialize flowy from saved output

### ISSUE THREAD

**Issue by unruledboy** [alyssaxuu/flowy#4]
We can use flowy.output to get the json data. Can we also initialize flowy with the data saved?

**Comment by alyssaxuu** [comment]
Yep, that's certainly something to be added in. I suppose the easiest way to go about it is to have the HTML outputted alongside the rest of the data in the JSON object, and then simply use that to import the data (& update the blocks array). Going to look into it!

**Comment by alyssaxuu** [comment]
Implemented a function to import flowcharts from outputted data.
