### ISSUE TITLE
I want to make contributions but don't know on which codebase

### ISSUE THREAD

**Issue by Jisco** [alyssaxuu/flowy#42]
Hi,
first of all, thank you for this great project. 👍 

I would like to make a few changes and/or extensions. Now, however, i doesn't know on which code base this should happen. Since a "few" pull requests from @joelvh are still open.

Will they be merged or something similar?

Until then, I will be working in my own [fork](https://github.com/Jisco/flowy).

There is already a "minimal" demo for easy access in development and a plugin to use templates.

It's a plugin because of this "future codebasis is unknown" problem, here :sweat_smile:

**Comment by alyssaxuu** [comment]
I'm personally not planning on merging. I like to keep the code as simple as possible, with fewer files, and while @joelvh's code is great, I would personally prefer to keep it as is.
