### ISSUE TITLE
<!DOCTYPE html> Breaks drag and drop

### ISSUE THREAD

**Issue by fcnyp** [alyssaxuu/flowy#44]
When adding `<!DOCTYPE html>` to as the first line in demo/index.html drag and drop interaction will break. Child elements will not reposition to parent and connectors will be offset.

To reproduce:
1. Add `<!DOCTYPE html>` to  first line of demo/index.html
2. Drag element to canvas, add second element to canvas connected to first
3. Click hold and drag first element then release

**Comment by alyssaxuu** [comment]
Just fixed it.

**Comment by fcnyp** [comment]
Thanks!
