### ISSUE TITLE
Drag and drop replacement off

### ISSUE THREAD

**Issue by fcnyp** [alyssaxuu/flowy#45]
With the recent change to the library when moving linked items repeatedly each release offsets the connector and the parent block slightly. If you drag and drop the same two blocks about 20 times its easy to see. I believe this is related to the `<!DOCTYPE html>` change.

To reproduce:
1. Add block
2. Connect single child block
3. Drag parent block and reposition (5 or more times), each drag and drop will offset the connector and parent by a couple pixels.

**Comment by alyssaxuu** [comment]
Fixed!
