### ISSUE TITLE
.dragging not being removed

### ISSUE THREAD

**Issue by fcnyp** [alyssaxuu/flowy#49]
Have a condition in which the .dragging class is not being removed. I've been trying to reproduce, while I can replicate I can't put my finger on a series of moves to make it occur.

Alyssaxuu, you may know better of an edge condition that may make this occur, I'll keep trying to reproduce.

**Comment by fcnyp** [comment]
Got it.

1. Add block
2. Add child block to block 1
3. Add second child to block 1
4. Move first child under second child

This leaves the canvas with the original child under the second child and it retains the dragging class.

**Comment by alyssaxuu** [comment]
Fixed
