### ISSUE TITLE
ES6 over jQuery

### ISSUE THREAD

**Issue by unruledboy** [alyssaxuu/flowy#5]
One of the beauties of this project is to have minimum dependency, if we can use ES6 APIs to replace jQuery, it would be even more slim.

Like `Element.querySelector` over 1 element `$('selector')`, or `Element.querySelectorAll()` for multiple element `$('selector')`.

**Comment by Githamza** [comment]
I am strongly interested to know if  jQuery will be replaced by future js in future releases

**Comment by alyssaxuu** [comment]
That's definitely something that would greatly improve the library. I made it with jQuery for ease, but ES6 would remove all dependencies, making it even more minimal indeed. Going to look into it!

**Comment by Githamza** [comment]
I propose to create a new issue with list of next features to add. people could also submit their ideas in comments.

**Comment by DenysVuika** [comment]
This resource can help: http://youmightnotneedjquery.com/

**Comment by MarceloRGomes** [comment]
Uncaught TypeError: Cannot read property '0' of undefined
    at HTMLDivElement.e (flowy.min.js:1)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.v.handle (jquery.min.js:2)

**Comment by christianoerick** [comment]
TypeError: t.targetTouches is undefined264 flowy.min.js:1:11842

**Comment by alyssaxuu** [comment]
> Uncaught TypeError: Cannot read property '0' of undefined
> at HTMLDivElement.e (flowy.min.js:1)
> at HTMLDocument.dispatch (jquery.min.js:2)
> at HTMLDocument.v.handle (jquery.min.js:2)

> TypeError: t.targetTouches is undefined264 flowy.min.js:1:11842

Fixed those issues, was a small typo.

**Comment by benjaminaudet** [comment]
Did you begin to work on this @alyssaxuu ? I'm interested in fixing this issue in the two days comin'.
I like your work btw.

**Comment by alyssaxuu** [comment]
> Did you begin to work on this @alyssaxuu ? I'm interested in fixing this issue in the two days comin'.
> I like your work btw.

I've been working on it, although I've been a bit busy.

**Comment by yellow1912** [comment]
I can help you if you need any help. Definitely interested in removing jquery altogether.

**Comment by alyssaxuu** [comment]
> I can help you if you need any help. Definitely interested in removing jquery altogether.

Feel free to contribute ^^ I haven't really done much progress with it yet since I don't have the time for it right now, I could dive into it this weekend.

**Comment by diegonvs** [comment]
https://github.com/google/closure-library/tree/master/closure/goog can be another resource for good and wide-compat code :)

**Comment by diegonvs** [comment]
How can we split tasks? 🤔

**Comment by benjaminaudet** [comment]
I've begin to work on my fork. I've start cleaning the code, begin to use ES6 features, but not yet moving from JQuery to plain javascript. I guess we could define some types of JQuery calls, group them by category and each of us takes care on his category, what do you think about that ?

**Comment by yellow1912** [comment]
I think we can do that: splitting the features to make it easier to collaborate. 

Code can be written in ES6 then ported back to ES5 using the Babel transpiler.

**Comment by Zert3x** [comment]
So I'm not that great at javascript, but I have a lot of time on my hands so I did my best at converting to ES6.  There are some issues with alignment that are probably happening due to my inexperience, but hopefully it's useful to you. [My fork](https://github.com/Zert3x/flowy)

**Comment by alyssaxuu** [comment]
The project officially has no dependencies - got rid of jQuery! Thanks everyone for your contributions :)
