### ISSUE TITLE
how do the flowy use in the vue project?

### ISSUE THREAD

**Issue by wulinsheng123** [alyssaxuu/flowy#52]
`<body>
    <div class="create-flowy">The block to be dragged</div>
    <div id="canvas"></div>
  </body>

  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/gh/alyssaxuu/flowy/flowy.min.css"
  />
  <script src="https://cdn.jsdelivr.net/gh/alyssaxuu/flowy/flowy.min.js"></script>
  <script>
    var spacing_x = 40
    var spacing_y = 100
    // Initialize Flowy
    flowy(
      document.getElementById('canvas'),
      onGrab,
      onRelease,
      onSnap,
      onRearrange,
      spacing_x,
      spacing_y
    )
    function onGrab(block) {
      // When the user grabs a block
    }
    function onRelease() {
      // When the user releases a block
    }
    function onSnap(block, first, parent) {
      // When a block snaps with another one
    }
    function onRearrange(block, parent) {
      // When a block is rearranged
    }
  </script>`
why can't ran

**Comment by yellow1912** [comment]
It's the best to create a component for flowy. Initialize flowy inside your `mounted` hook.

**Comment by wulinsheng123** [comment]
it can't run 
![image](https://user-images.githubusercontent.com/27261522/79728787-0a687a00-8321-11ea-8337-2623b5f63ab2.png)

**Comment by wulinsheng123** [comment]
i sent one of my code picture

**Comment by wulinsheng123** [comment]
> It's the best to create a component for flowy. Initialize flowy inside your `mounted` hook.

please could you hlep me with my project

**Comment by wulinsheng123** [comment]
> > It's the best to create a component for flowy. Initialize flowy inside your `mounted` hook.
> 
> please could you hlep me with my project

no wrong no log it only can't run

**Comment by yellow1912** [comment]
Can you create a code pen? https://codepen.io/

**Comment by wulinsheng123** [comment]
> It's the best to create a component for flowy. Initialize flowy inside your `mounted` hook.

https://codepen.io/wulinsheng123/pen/povrrKg

**Comment by wulinsheng123** [comment]
> 您可以创建一支数字笔吗？https://codepen.io/

Can the last multiple tags be merged into one

**Comment by AllanOricil** [comment]
Im tried the same things. Nothing worked. I think we need to open a Enhancement feature.

**Comment by wulinsheng123** [comment]
> Im tried the same things. Nothing worked. I think we need to open a Enhancement feature.
don't worry it's can work in the vue

**Comment by wulinsheng123** [comment]
> Im tried the same things. Nothing worked. I think we need to open a Enhancement feature.

i will help you

**Comment by AllanOricil** [comment]
> > Im tried the same things. Nothing worked. I think we need to open a Enhancement feature.
> 
> i will help you

Sure. Add me on linkedin so we can discuss there. My username on linkedin is Allan Oricil.

**Comment by wulinsheng123** [comment]
> > > Im tried the same things. Nothing worked. I think we need to open a Enhancement feature.
> > 
> > 
> > i will help you
> 
> Sure. Add me on linkedin so we can discuss there. My username on linkedin is Allan Oricil.

do you have the facebook?

**Comment by wulinsheng123** [comment]
> > > Im tried the same things. Nothing worked. I think we need to open a Enhancement feature.
> > 
> > 
> > i will help you
> 
> Sure. Add me on linkedin so we can discuss there. My username on linkedin is Allan Oricil.

i sent message to you

**Comment by wulinsheng123** [comment]
> > > Im tried the same things. Nothing worked. I think we need to open a Enhancement feature.
> > 
> > 
> > i will help you
> 
> Sure. Add me on linkedin so we can discuss there. My username on linkedin is Allan Oricil.

wechat?

**Comment by techjewel** [comment]
Any update about this implementation? Anyone could do it?

**Comment by techjewel** [comment]
Any update about this implementation? Anyone could do it?
