### ISSUE TITLE
OnSnap not working properly

### ISSUE THREAD

**Issue by pilootchoum** [alyssaxuu/flowy#56]
Hello,

When trying to prevent the snap from one block using the onsnap function and returning false,
it does not work as expected.

I tried also on the demo page just returning false, and once the bloc is released, it is not attached to the parent one (good), but the dragged block itself stay on the canvas kind of lost.

Attached a screenshot.
![image](https://user-images.githubusercontent.com/1533159/80226082-3602a180-864c-11ea-9a6e-12d35c217847.png)

Then as soon as you try to drag another block, the previous one (the lost one) move to the top of the window.

![image](https://user-images.githubusercontent.com/1533159/80226141-487cdb00-864c-11ea-8251-6c2e6cf9ed44.png)

There is no javascript error, but you can see in the dom that the lost/dragged block is added in the dom at the root at the dom, whereas it should simply not be there.

![image](https://user-images.githubusercontent.com/1533159/80226354-8c6fe000-864c-11ea-8c83-4ff2c06acb9a.png)

**Comment by alyssaxuu** [comment]
Just fixed it.
