### ISSUE TITLE
Enhancement - Allow snapping of blocks by type

### ISSUE THREAD

**Issue by imeneses** [alyssaxuu/flowy#60]
This is not an issue but more of a feature request, could there be a way to only allow certain types of blocks to attach to others, like in your demo only allow Actions and Loggers to be attached to a Trigger block.
Thank you!

**Comment by alyssaxuu** [comment]
This is already a feature, you can use onSnap which gets triggered when a block can attach to another block, and use the parent parameter + the current block to determine on your end if the blocks can attach or not. Just return false to prevent the attachment.

Let me know if that helps.

**Comment by imeneses** [comment]
Do you mean this function on the demo? function snapping(drag, first)

**Comment by alyssaxuu** [comment]
> Do you mean this function on the demo? function snapping(drag, first)

Yes, exactly. [Here](https://github.com/alyssaxuu/flowy#on-snap) is how it works.

**Comment by imeneses** [comment]
I am having issues getting the value out of the parent block.  parent.querySelector(".blockelemtype").value returns Uncaught TypeError: parent.querySelector is not a function

**Comment by imeneses** [comment]
These are the only properties I get from parent, I can't access the value property
{"parent":-1,"childwidth":318,"id":0,"x":1158,"y":327,"width":318,"height":120}

**Comment by alyssaxuu** [comment]
Oh oops, this is clearly an oversight from my part as the parent property of the on snap method should return a DOM element and not the array. I've just fixed it, so now you can access the div to get the value.

**Comment by imeneses** [comment]
Thank you so much! Worked perfectly :)

**Comment by imeneses** [comment]
One more question, to filter what block can be the root block, the first one in the canvas, I should filter in flowy.endDrag or in the snapping function? If I do it in snapping it seems to attach it anyway. Thank you!
