### ISSUE TITLE
Add blocks without snap, and then join them as you want

### ISSUE THREAD

**Issue by AllanOricil** [alyssaxuu/flowy#63]
I want to be able to drag blocks into the "canvas" and later join them as I want. Without the snap thing.

**Comment by alyssaxuu** [comment]
Unfortunately the automatic snapping is basically the core of the library, so this is definitely something I am certainly not going to add. There are other Javascript libraries out there that allow for that functionality specifically, for example [jQuery.flowchart](http://sebastien.drouyer.com/jquery.flowchart-demo/).
