### ISSUE TITLE
Any plans for conditional flow blocks?

### ISSUE THREAD

**Issue by joshbedo** [alyssaxuu/flowy#64]
This would be super useful for routing logic. For example

1. new lead
2. if new lead has tag X do this else do this.

If not I'd be open to brainstorming something and possibly submitting a PR or something :)

**Comment by jamessampford** [comment]
A block (new lead) can have multiple children, so one child block can be if tag = X and the other child block can be if tag != X

**Comment by joshbedo** [comment]
Great! makes sense excited to start building this out connect it with a job queue

**Comment by johndkn** [comment]
Hi @joshbedo,
This is also being discussed here : #29 :)

**Comment by alyssaxuu** [comment]
Closing issue as it is a duplicate of #29.
