### ISSUE TITLE
Formatted Version of Flowy.min

### ISSUE THREAD

**Issue by MohammadAhmad1990** [alyssaxuu/flowy#68]
Hi,
Great work. Could you please add formatted version of the flowy.min.js, I want to understand this library in dept so it will be easy to contribute and add new features. 

Regards

**Comment by dmlnc** [comment]
@MohammadAhmad1990  Check here https://github.com/alyssaxuu/flowy/blob/master/engine/flowy.js

**Comment by MohammadAhmad1990** [comment]
Thank you.
