### ISSUE TITLE
Adding blocks programmatically

### ISSUE THREAD

**Issue by fj-iv** [alyssaxuu/flowy#69]
I'm creating an 'on rails' control flow diagram where users are guided trough the process and they have limited options regarding the kind of block/condition they can add depending on the level they are. For this reason I want to limit the drag & drop feature and instead have an 'add' button below every block.
What would be a good a approach for this? I've tried mimicking mouse events with little succes and export/edit/import of the diagram config but I am unsure about what parameters are mandatory. Do I need a valid HTML structure, is it created from blocks/blockarr?
Any help/input is welcome and of course, if I get this workign and anyone else is interested I'll make it available for everyone.

Thanks.

**Comment by yellow1912** [comment]
https://github.com/alyssaxuu/flowy/issues/53

I think this is the issue to follow
