### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by Ademking** [alyssaxuu/flowy#7]
Thank you for this awesome library. Keep up the good work!
Do you plan to make it works with Angular?

**Comment by alyssaxuu** [comment]
I don't have any plans to make it work with Angular currently ^^

**Comment by Githamza** [comment]
If it's packaged to npm, I think it will be possible to include in Angular ?

**Comment by nicksav** [comment]
Angular 9 version, if this will help - https://github.com/remodzy/ng-flowy
