### ISSUE TITLE
Conditionals and finalising the process in one node are not allowed

### ISSUE THREAD

**Issue by jlmrobles** [alyssaxuu/flowy#71]
Hello Alyssa,

First of all congratulations for this excellent work. It is very helpful.

I would like to know if you can confirm that the current code is not possible to do the actions as below:
- Conditional node
- That the process finalizes in one node.

As an example, I have added a picture with the nodes/actions that I think is not allowed currently. I have marked them in red.

![Diagram](https://user-images.githubusercontent.com/41233768/83013069-ae2dff80-a01c-11ea-87de-c0e63c54b92f.png)
 
Could you update the code with these actions?

I'm looking forward to hearing from you,

all my best,

José

**Comment by alyssaxuu** [comment]
Yeah, this kind of flowchart is not possible with Flowy, and I don't think it's something I'm planning to add anytime soon. It would come with its own set of problems conflicting with the current structure for the library.

I would say that what you're looking for is not something like Flowy but rather a flowchart diagram library like https://flowchart.js.org/ that is more "technical" and has those different kinds of blocks to represent a process/activity differently.

I suppose if there was enough interest in adding specific blocks, such as a block with multiple arrows coming towards it or with 2 arrows placed on the sides I could look into it, but so far I haven't really seen such interest.

**Comment by jlmrobles** [comment]
Thanks, Alyssa, for your comments.

I have shown the structure using draw.io only to explain to you the issue graphically. 
The idea is to use all the resources that you have proposed with your library that essentially is very similar than Salesforce - Pardot. Do you know it?

I copy an image of Pardot Workflow builder

![image](https://user-images.githubusercontent.com/41233768/83282531-03634000-a1da-11ea-8f68-c624ca9ec87e.png)

I think te solution regarding usability maybe needs to be focused on:

1.- When you start the creation process of the flow the system will generate an End Node automatically.
2.- The connections that now you propose on the bottom of every element need to be outside of the element like a (+) as you can see in the image attached, as Pardot does.
3.- Some actions as forks need to be set up into the node would indicate the number of branch and conditionals.

What do you think about it? 

I'm looking forward to hearing from you,

best regards,

**Comment by alyssaxuu** [comment]
I want to keep the library simple with automatic connections and a simplistic design (simple arrows and blocks that the developer can fully customize). So adding a "+" symbol or an end node after you start creating the flowchart is definitely out of the question.

But like I mentioned previously I will explore the possibility of creating blocks with custom properties such as an end block or an IF block, as this would be optional and might actually be useful.

**Comment by jlmrobles** [comment]
Yes, creating a block with custom properties could be a great way instead of modifying your design. I would like you can consider quickly and we can see a new release of flowy with this new feature that allow creating blocks with properties than control the workflow.

**Comment by alyssaxuu** [comment]
> Yes, creating a block with custom properties could be a great way instead of modifying your design. I would like you can consider quickly and we can see a new release of flowy with this new feature that allow creating blocks with properties than control the workflow.

Unfortunately I am planning a big release with a lot of new features & refactoring of the code that might take a couple of months to complete. I don't want to keep pushing to the repo for individual changes as it makes it hard for developers who are using the library to stay up to date, so I'm only doing that for now for bug fixes.

**Comment by AsimNet** [comment]
I suggest replacing the current parent/children, to something like: node and links.
each link has two properties essentially: {from: node_id, to: node_id}

in that way, creating a branch/conditionals nodes will be easy.

thank you.

**Comment by alyssaxuu** [comment]
I will close this issue as the main one is #29 :)
