### ISSUE TITLE
Return to previous position on snap. 

### ISSUE THREAD

**Issue by kurumbus** [alyssaxuu/flowy#72]
Hello! Thank you for a wonderful library.

So the issue for is that if you snap a block on some empty space it gets deleted. For us, the ideal would be to either rearrange it (as it currently is), but if someone snaps on an empty space - just return to the initial position. To be honest i kind of understand that it has something to do with  `release()` or `snapping()` callbacks but don't know what exactly lol

I've read a couple of similar issues, but I can't understand what I should do. :-/
#48 #32 perhaps #57

**Comment by alyssaxuu** [comment]
Yes, the idea is to use the method "on rearrange" to prevent the block from being deleted and instead go back to the previous position. Here's how you can do that:

- First, create a rearrange function in your javascript file, like this (if you return true, the block won't get deleted and instead go to the previous parent):

```javascript
function onRearrange(block, parent){
	// When a block is rearranged
	return true;
}
```

- Then, make sure to include it when you initialize flowy (currently while all the parameters except for the first one are optional, you must include the previous ones, but you can simply use the default functions shown in the documentation for each of the methods):

```javascript
flowy(document.getElementById("canvas"), onGrab, onRelease, onSnap, onRearrange, spacing_x, spacing_y);
```
