### ISSUE TITLE
Browser resolution and object placement

### ISSUE THREAD

**Issue by fcnyp** [alyssaxuu/flowy#77]
Having an error that if a Flowy configuration is saved at one browser resolution and imported at smaller resolution the arrows are not placed correctly on the virtual axis and blocks collide on snapping. 

For instance I saved at a large resolution and imported at a smaller and all the arrows were placed above the blocks. When I click drag and snap a block and the rearrange occurs the blocks and arrows may overlap and or collide rendering the diagram unreadable.

**Comment by alyssaxuu** [comment]
By resolution I assume you mean resizing the browser window? Or zoom? I'll look into it.

**Comment by fcnyp** [comment]
Browser window, not zoom thanks =)

**Comment by alyssaxuu** [comment]
Hmm I think I know why, it's probably due to the RearrangeMe function being called right after import, which modifies the position of the blocks and arrows. I'll try to see if I can reproduce the issue, it still feels odd that the blocks and arrows would be crammed together regardless...

**Comment by fcnyp** [comment]
When it happens I'll have multiple blocks stacked on top of each other each slightly lower then the one behind it.

**Comment by MisterT81** [comment]
https://bitcoinchaser.com/best-bitcoin-bonuses-july-2020/

**Comment by fcnyp** [comment]
Narrowed this down a little more, there is something occurring at line 177 when `arrowParent.style.top` is set.

I can't reproduce it reliably. What I have identified is:
1.) Added `console.log('${w}: (${arrowParent.getBoundingClientRect().top} + ${window.scrollY}) - (${canvas_div.getBoundingClientRect().top} + ${canvas_div.scrollTop}) - 1 + "px";');` to line 178.
2.) Move child blocks then move root block
3.) If error does not occur after root block is moved all arrows and blocks draw correctly and the following is printed:
```
1: (310.046875 + 0) - (53.296875 + 0) - 1 + "px";
2: (310.046875 + 0) - (53.296875 + 0) - 1 + "px";
3: (508.046875 + 0) - (53.296875 + 0) - 1 + "px";
4: (508.046875 + 0) - (53.296875 + 0) - 1 + "px";
5: (718.546875 + 0) - (53.296875 + 0) - 1 + "px";
```
4.) If the error DOES occur after root block is moved all arrows move up by ~ px, if moved again all arrows will move up again by ~ px. The following is printed:
```
1: (225.046875 + 0) - (53.296875 + 3) - 1 + "px";
2: (225.046875 + 0) - (53.296875 + 3) - 1 + "px";
3: (423.046875 + 0) - (53.296875 + 3) - 1 + "px";
4: (423.046875 + 0) - (53.296875 + 3) - 1 + "px";
5: (633.546875 + 0) - (53.296875 + 3) - 1 + "px";
```
5.) When the error does present itself the 3, or the value of `canvas_div.scrollTop` has been anything from 1 to over 300. The arrows will shift up by that many pixels.

**Comment by fcnyp** [comment]
Was able to recreate with the live demo code on https://alyssax.com/x/flowy/.

1.) add 1 block to the middle of the page then add 5 blocks, each on under the first (more if needed, you want to have a large scroll area)
2.) scroll down the page to where the first block you added is now at the top of your view area, you should have a small amount of scroll space above this
3.) drag the first, original block. All arrows will now shift up by the amount of scroll area you have left at the top

**Comment by alyssaxuu** [comment]
Just fixed this, didn't account for the canvas scroll position for the arrows in a section of the code :)
