### ISSUE TITLE
Dynamic vertical height and sub-element connectors

### ISSUE THREAD

**Issue by aadityak** [alyssaxuu/flowy#79]
As with popular flow designers, can new elements be added vertically instead of horizontally?

This gives a lot of scalability for the flow diagrams. E.g: in a block, a lot of times you want to have more than just yes/no conditions. Each condition 'inside' the block is now connected with other blocks rather than a single straight line just connecting the two blocks.

This will work as infinite conditional blocks and give plenty of room to add any number of elements that the end user would like.

<img width="254" alt="chrome_F16i0Hu13q12" src="https://user-images.githubusercontent.com/2543291/85916066-a1ded180-b86a-11ea-95f4-be9bc24c0bec.png">

**Comment by alyssaxuu** [comment]
Not sure I completely understand. You mean being able to "grow" the blocks dynamically after placing them by adding smaller blocks within them?

**Comment by aadityak** [comment]
Yes. This can also serve as conditional blocks.

After a block is placed with 2 questions yes and no. A user then adds 2 more questions to the list e.g. not sure, skip question. So you now have a list with 4 list elememts which you can dynamically modify from user properties.

In this case, these list elements can be connected with new blocks. Instead of a line connecting two blocks, you can now draw lines connecting each seperate list element with blocks to denote if (condition), else if(condition)...

On the block, <ul> and <li> tags seem to be working as shown in the screenshot. I am not sure how to draw lines connecting seperate list elements and blocks.

**Comment by alyssaxuu** [comment]
Got it, so in regards to changing the height of the blocks dynamically (or width or any property) & updating the tree, yes, this is definitely in the roadmap as requested in #53 (for a dedicated render method to redraw the tree properly). As per drawing lines within the block or implementing a way to drag blocks within other blocks, I am not going to add this in as it breaks with the simplicity of Flowy, and should be up to the developer to implement depending on their use case.

I will close this issue as the aspect I am going to be working on is already mentioned in #53 and in that sense it would be a duplicate.
