### ISSUE TITLE
Multiple parent blocks

### ISSUE THREAD

**Issue by benhid** [alyssaxuu/flowy#8]
In some cases, components may have two or more parents, which potentially could lead to these scenarios (not currently supported by flowy):

```
    +-------+ +-------+
    |       | |       |
    +-+---+-+ +---+---+
      |   |       |
      |   |       |
   +--+   +--+ +--+
   v         v v
+--+--+    +-+-+-+
|     |    |     |
+-----+    +-----+
```

```
    +-------+      +-------+
    |       |      |       |
    +-+---+-+      +---+---+
      |   |            |
      |   |            |
   +--+   +--+         |
   v         v         v
+--+--+   +--+--+   +--+--+
|     |   |     |   |     |
+-----+   +--+--+   +--+--+
             |         |
             |         |
             +--+   +--+
                v   v
              +-+---+-+
              |       |
              +-------+
```

**Comment by alyssaxuu** [comment]
Could be implemented into the library, although I'm not too sure on the expected user behaviour here. What would happen if a user drags a block near there? What if the parent blocks aren't one next to the other but rather have blocks in-between (e.g. instead of the 2nd & 3rd block in the second row, being the 1st and 3rd block)?

Appreciate insight, but yeah it's currently not something that would work with the simplistic behaviour of my library (which is meant to be minimal).

**Comment by bestwestern** [comment]
I suggest it would require the user to hold down ctrl(/... or right click) while dragging existing block to the desired second parent.

**Comment by benhid** [comment]
I get your point, one possible way of dealing with this issue would be to re-design the "snapping" process to allow dragging-and-dropping blocks and edit the connections between them ([take a look here](http://sebastien.drouyer.com/jquery.flowchart-demo/)), so the user would first place all the desired blocks in the canvas and then add connections.

(In the future, this could also allow to define multiple inputs/outputs for a block).

Flowy is intented to be minimal, which is fine. But *I think* that this limitation -regarding multiple parents- is a determinant factor in choosing a library to create flowcharts.

**Comment by alyssaxuu** [comment]
That's a mechanic I've purposefully drifted away from to keep my engine simple & straightforward. I saw multiple libraries out there where you had to make the connections yourself and many times didn't even have the drag and drop behaviour, you had to click on a block and then select where you wanted to add another block & of which type (e.g. Whimsical).

Maybe I could add some new methods to manually attach blocks so if somebody wants to be able to have blocks with multiple parents, they could implement it however they see fit (using the methods).

**Comment by benhid** [comment]
Thinking about it, how the layout would be reorganized when adding a second parent? 🤔

**Comment by alyssaxuu** [comment]
Yeah, that's one of the main issues I see with this functionality. If the parents are in the same level, it should be sort of easy, but the block would be pushed down if the blocks in between the parents have children. If the blocks are in different levels then that's a whole other story.

**Comment by benhid** [comment]
What if we could drag-and-drop blocks at any place of the canvas without creating any connection at all? And then -once the block is on the canvas- we could drag and drop it over another block(s) to create a new connection.

This would require a new method for deleting blocks instead of splitting branches.

<img width="1029" alt="example" src="https://user-images.githubusercontent.com/6999898/70071113-1911f700-15f5-11ea-8756-2baa6cc9b132.png">

**Comment by alyssaxuu** [comment]
Interesting, although not sure if it's still the most intuitive. I'm happy with the automatic snapping, it makes it quick and simple. If there has to be added an extra step, that would make it slower and possibly harder to understand. Having a user drop a block anywhere on the canvas could work if I introduced the possibility to have multiple trees at once that said, so I might be able to come up with a better solution when I implement the multiple tree functionality.

**Comment by Githamza** [comment]
@alyssaxuu  I think we could have two types of connecting behaviour: the auto and the manual  snapping .
The auto when adding a block from left menu and the manual to modify the actual graph. 
the complicated part to develop is drawing connection lines when multi parents don't have the same level. For that, I have an I idea which is to let user draw connection line when snapping from output to input and render only horizontal and vertical lines . so that you don't have to treat connection behaviour. 
I understand that this features breaks the actual idea of graph but I'm convinced that it will open this tool to a large community because a flow in many cases have external dependencies ( multi tree/parents )

**Comment by bienek** [comment]
Hi Alyssa, I admire and totally understand your intention to keep Flowy as simple as possible. However there's a bonus in having multiple parents: you could model conditional flows using if-blocks (as requested in [issue #29](https://github.com/alyssaxuu/flowy/issues/29)). Atm it seems to be a blocker for many who would like to use your lib and this feature would make Flowy so much more valuable. Keep up the good work!

**Comment by sfmskywalker** [comment]
It's true, Flowy's simplicty makes it very attractive to use. But as @bienek mentioned, the ability to have multiple parents would allow me (and no doubt many others) to actually use Flowy as the ultimate flowchart designer in my Elsa Workflows project.

**Comment by alyssaxuu** [comment]
> It's true, Flowy's simplicty makes it very attractive to use. But as @bienek mentioned, the ability to have multiple parents would allow me (and no doubt many others) to actually use Flowy as the ultimate flowchart designer in my Elsa Workflows project.

Yes, I understand. It's just not the objective of this library, there are lots of great options out there with very intricate functionality. I made a library that people who weren't super knowledgeable or just wanted a quick way to implement flowcharts in their projects could use, that was and is still my target audience.

I might consider doing something like you mention in the future, but in any case, I would like to keep Flowy as it is, and maybe offer a more complex, "corporate" oriented solution for power users.

**Comment by sfmskywalker** [comment]
I understand. Thanks for responding, and keep up the great work!

**Comment by alyssaxuu** [comment]
Closing this issue as it's not currently feasible with how the library is set up (and I can't think of an intuitive way to implement the behaviour to add multiple parents).
