### ISSUE TITLE
Flowy not working in IE browser

### ISSUE THREAD

**Issue by yogi40911** [alyssaxuu/flowy#82]
I have implement flowy Js in my application.But it is not working in IE browser ,working fine in Chrome browser.
Error getting in IE browser classlist.add is not working .
can you please suggest me a solution ?.

**Comment by alyssaxuu** [comment]
I assume you're using IE9 or lower? https://developer.mozilla.org/en-US/docs/Web/API/Element/classList (see compatibility chart)

It seems that the property is only available from IE10 onwards. I could try replacing it with `className +=` which does seem to have support. I will look into it.

**Comment by jamessampford** [comment]
IMO support for anything pre IE 11 shouldn’t exist since Microsoft doesn’t even support them, anyone using those browsers should have a prompt to upgrade, for their own security more than anything

**Comment by alyssaxuu** [comment]
> IMO support for anything pre IE 11 shouldn’t exist since Microsoft doesn’t even support them, anyone using those browsers should have a prompt to upgrade, for their own security more than anything

I think you're right. It's likely other properties might not be compatible either so it would be counter productive to try to make it work for old browsers. I don't think it's worth fixing in that case.
