### ISSUE TITLE
Drag n drop not working in IE browser

### ISSUE THREAD

**Issue by yogi40911** [alyssaxuu/flowy#83]
Drag n drop not working in IE browser.
I think in JS file there are property which are not supported by IE may causing issue,can you please help me with a solution?
I have attached my error and IE versions.

![Error in IE](https://user-images.githubusercontent.com/67190347/86512474-3f647300-be20-11ea-8acc-c0b3a1cdd739.png)

![IE version](https://user-images.githubusercontent.com/67190347/86512376-5eaed080-be1f-11ea-9ebd-3cc9bae38e8d.png)

**Comment by alyssaxuu** [comment]
Just added a workaround for IE11 (https://stackoverflow.com/questions/59455136/how-to-support-closest-in-ie11). Should work now (also updated the live demo).
