### ISSUE TITLE
Not able to drop element 

### ISSUE THREAD

**Issue by yogi40911** [alyssaxuu/flowy#85]
I tried your previous issue solution for closet which worked thanks.
But now i am facing another issue with IE ,element is dragged but it is not dropped, it again move to its own place .
(classList property is not working in IE )

Even i am not getting any error in console ,can you please help me with this solution ?
It will be helpful.
I shared my IE version .

Thanks.

![IE 11 version](https://user-images.githubusercontent.com/67190347/86727999-9bf6a680-c049-11ea-8aec-afb897889d81.png)

**Comment by alyssaxuu** [comment]
I see, apparently IE11 does support classList but not for SVG which is what I use for the arrows. Being quite frank with you I don't think it's productive to keep trying to support the browser, it's simply counter intuitive and preventing me from using a lot of features that are available in pretty much all the other browsers. Microsoft released Edge to replace Internet Explorer, so I just don't personally see the point unfortunately. It just overcomplicates things.
