### ISSUE TITLE
Undo / Redo

### ISSUE THREAD

**Issue by prakashgp** [alyssaxuu/flowy#86]
If a child block is moved away and not properly snapped to parent block then entire tree is vanished. So an option to undo this would be good idea. 
By the way, I appreciate your hard work.

**Comment by alyssaxuu** [comment]
Undo/Redo would IMO be added by the developer when integrating this library. I am aware that the functionality isn't there yet - but basically the idea is to create a render method (see #53) that would allow to redraw a tree any point in time, undoing or redoing. It's on the roadmap, but yeah I do not plan to add a dedicated undo/redo function as I don't think it would make sense for the library to come with it.
