### ISSUE TITLE
Large flowchart causes misalignment.

### ISSUE THREAD

**Issue by Kannndev** [alyssaxuu/flowy#89]
@alyssaxuu Thanks for the wonderful library. 
There is a misalignment issue when we have a large flowchart. Please find the attached file for more reference. Please help us in resolving this.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23332484/88774673-5b4e0100-d1a1-11ea-8fef-bce32c98d4d6.gif)

**Comment by Kannndev** [comment]
This issue is not only happening in the 1st level But anywhere down the line where we have multiple branches splitting up and there is a horizontal scrollbar this seems to happen.

**Comment by alyssaxuu** [comment]
Just fixed it, it was an issue to do w/ the offset applied to the tree on the left (to prevent it from being pushed to the left side of the canvas, since the horizontal scrollbar doesn't expand in that direction), I didn't take the offset into consideration in that situation.

**Comment by Kannndev** [comment]
Thanks so much, @alyssaxuu . That was a quick resolve
