### ISSUE TITLE
Ability to group sections

### ISSUE THREAD

**Issue by andyhoyle** [alyssaxuu/flowy#9]
I have a specific requirement to be able to add one or more nodes to a group.

``` 
             ----------------
             |               |
             |    -------    |
             |    |  A  |    |
             |    -------    |
             |       |       |
             |       \/      |
             |    -------    |
             |    |  B  |    |
             |    -------    | 
             |       |       |
             --------|--------
                     |
         ----------------------
         |                    |
         |                    |
  -------|--------     -------|--------
 |       \/      |    |       \/      |
 |    -------    |    |    -------    |
 |    |  C  |    |    |    |  E  |    |
 |    -------    |    |    -------    |
 |       |       |    |       |       |
 |       \/      |    |       \/      |
 |    -------    |    |    -------    |
 |    |  D  |    |    |    |  F  |    |
 |    -------    |    |    -------    | 
 |               |    |               |
 ----------------     ---------------- 
```

**Comment by alyssaxuu** [comment]
How would you expect those groups to work? Visually have a block wrapping the blocks? Not exactly sure if this would add further complexity to my engine, which is meant to be minimal. You could consider the groups to be the blocks by themselves and already include the blocks inside them, or simply implement it via cosmetics.

**Comment by andyhoyle** [comment]
Yes a block wrapping the blocks - even if its a simple grey rectangle. The reason is to allow modelling of code. The groups are services, or modules. The blocks within them are methods which call other methods in the current service or in another service.

**Comment by alyssaxuu** [comment]
Closing this as this could be implemented by the developer by creating a single block with the rest embedded within it. #29 *could* also be considered a similar issue but it might be more doable by creating the following unit, used as a group (Text message block together with "Yes" and "No"):

![image](https://user-images.githubusercontent.com/7581348/80231154-d2ef1b80-8607-11ea-999c-ab7b2adf9fac.png)
