### ISSUE TITLE
Can we make canvas auto scrollable when block gets out of view while dragging

### ISSUE THREAD

**Issue by Kannndev** [alyssaxuu/flowy#90]
@alyssaxuu right now when we drag a block to the left the canvas does not scroll. So the user will not know which block it gets attached to or whether its going to removed. It applies to all scroll directions. It would be better if we could somehow scroll the canvas when it goes out of view.

**Comment by alyssaxuu** [comment]
Sure why not. Just added it in ^^

**Comment by Kannndev** [comment]
Awesome, That was so quick. Thanks @alyssaxuu
