### ISSUE TITLE
Blocks misaligned after snap

### ISSUE THREAD

**Issue by fcnyp** [alyssaxuu/flowy#91]
Having a block snap alignment issue, arrows and blocks are misplaced after snap.

To recreate:
1.) Add root block to middle of page
2.) Add 2 children to root
3.) Add 5 or more grandchildren to each child leaving you with a root node and two columns that scroll Y
4.) Scroll to where root block is at the top of the page
5.) Move root block to the right dragging the whole tree over
6.) Click and hold the right child to the root, drag away then drag back to root and snap it back to root (expected behavior is no change) and arrows and blocks will be misaligned when snapping back

**Comment by alyssaxuu** [comment]
Hmm I'm not able to recreate this, it works fine for me. Are you using the latest version (there were several updates today fixing multiple issues)?

**Comment by fcnyp** [comment]
Latest update fixed. Thanks!
