### ISSUE TITLE
Question: Variable node height and arrows

### ISSUE THREAD

**Issue by fcnyp** [alyssaxuu/flowy#92]
Have a situation where my nodes may have different heights. What I'm seeing is that when this occurs the arrow line starts at the original location, as if the node was the default height. Is there a method to adjust the arrows to the variable height of the node?

**Comment by alyssaxuu** [comment]
Hmm, I don't see any problems w/ arrows (although I just made a fix having to do with the blue pulse indicator being misplaced with dynamic blocks. Maybe you could check it out again?

<img width="1143" alt="Screen Shot 2020-07-29 at 7 28 42 PM" src="https://user-images.githubusercontent.com/7581348/88832863-b7c91480-d1d1-11ea-9c8a-257d94acb1e0.png">

**Comment by fcnyp** [comment]
I can't merge that change in, my css differs so much now that change breaks the indicator all together =/

**Comment by alyssaxuu** [comment]
> I can't merge that change in, my css differs so much now that change breaks the indicator all together =/
> 
> Where does the arrow start position get set? I'll have to start there.

Agh I see. It gets set at the rearrangeMe function, the variable arrowy (which is then added as a SVG coordinate to draw the arrow). I'm not sure what version you have, you'd just have to make sure that the block height is taken into consideration + get rid of getComputedStyle(), I'm not sure why that was in there in the first place but it doesn't give accurate values.

I'll close this as it's not a library-specific issue, if you need more help though feel free to reach out :)
